# Generated by Django 4.2.2 on 2023-06-17 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('INN', models.CharField(max_length=14)),
                ('is_beneficiary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_list', models.ManyToManyField(to='users.users')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.users')),
                ('is_active', models.BooleanField(default=True)),
                ('Queue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Queue', to='users.queue')),
            ],
            bases=('users.users',),
        ),
    ]
